"""PostGIS adapter for the SpotStore seam.

The geometry column is the canonical WGS84 location. Callers continue to pass
longitude/latitude at the domain boundary; SQL readers derive them with
ST_X/ST_Y.
"""

from __future__ import annotations

import json
from datetime import datetime

import psycopg

from spot_intake.extract import classify_place_name, normalize_comment_keyword, normalize_comment_keyword_category, refine_precision


SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT DEFAULT 'douyin', keyword TEXT, title TEXT, url TEXT UNIQUE,
  author TEXT, publish_time TEXT, raw_text TEXT, collected_at TEXT
);

CREATE TABLE IF NOT EXISTS fishing_spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE,
  place_name TEXT, query_name TEXT,
  location geometry(Point, 4326),
  fish_species TEXT, fish_species_source TEXT, fish_confidence DOUBLE PRECISION,
  geocode_score INTEGER, geocode_level TEXT, confidence DOUBLE PRECISION,
  source_type TEXT, source_text TEXT,
  quality_score DOUBLE PRECISION, quality_score_source TEXT, quality_score_detail TEXT,
  precision TEXT, created_at TEXT
);
CREATE INDEX IF NOT EXISTS fishing_spots_location_gix ON fishing_spots USING GIST (location);
CREATE INDEX IF NOT EXISTS fishing_spots_video_id_idx ON fishing_spots (video_id);

CREATE TABLE IF NOT EXISTS video_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE,
  author TEXT, text TEXT, comment_time TEXT, comment_time_raw TEXT,
  comment_time_standard TEXT, ip_location TEXT, is_author BOOLEAN DEFAULT FALSE,
  raw_json TEXT, collected_at TEXT
);
CREATE INDEX IF NOT EXISTS video_comments_video_id_idx ON video_comments (video_id);

CREATE TABLE IF NOT EXISTS comment_keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE,
  comment_id BIGINT REFERENCES video_comments(id) ON DELETE CASCADE,
  keyword TEXT, category TEXT, confidence DOUBLE PRECISION, evidence TEXT,
  source TEXT, created_at TEXT,
  UNIQUE(comment_id, keyword, category)
);
CREATE INDEX IF NOT EXISTS comment_keywords_video_id_idx ON comment_keywords (video_id);

CREATE TABLE IF NOT EXISTS video_transcripts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT NOT NULL UNIQUE REFERENCES videos(id) ON DELETE CASCADE,
  status TEXT NOT NULL, transcript_text TEXT, audio_path TEXT, srt_path TEXT,
  model TEXT, error TEXT, raw_response_path TEXT, summary TEXT, extras_json TEXT,
  transcribed_at TEXT
);
"""


def init_db(conn: psycopg.Connection) -> None:
    """Create/upgrade the PostGIS schema and backfill deterministic fields."""
    conn.execute(SCHEMA_SQL)
    conn.execute("UPDATE fishing_spots SET source_type='video_text' WHERE source_type IS NULL OR source_type='' ")
    rows = conn.execute(
        "SELECT id, place_name, query_name, geocode_level FROM fishing_spots WHERE precision IS NULL OR precision=''"
    ).fetchall()
    for row_id, place_name, query_name, level in rows:
        precision = refine_precision(
            classify_place_name(place_name or ""),
            {"geocode_level": level or "", "query_name": query_name or ""},
        )
        conn.execute("UPDATE fishing_spots SET precision=%s WHERE id=%s", (precision, row_id))


class PostgisSpotStore:
    """SpotStore backed by PostgreSQL + PostGIS."""

    def __init__(self, database_url: str) -> None:
        self.database_url = database_url
        self.conn = psycopg.connect(database_url, autocommit=True)
        init_db(self.conn)

    def __enter__(self) -> "PostgisSpotStore":
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    def close(self) -> None:
        self.conn.close()

    def video_exists(self, url: str) -> bool:
        return self.conn.execute("SELECT 1 FROM videos WHERE url=%s LIMIT 1", (url,)).fetchone() is not None

    def upsert_video(self, keyword: str, video: dict) -> int:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        row = self.conn.execute(
            """INSERT INTO videos(platform, keyword, title, url, author, publish_time, raw_text, collected_at)
               VALUES('douyin',%s,%s,%s,%s,%s,%s,%s)
               ON CONFLICT(url) DO UPDATE SET url=EXCLUDED.url
               RETURNING id""",
            (keyword, video["title"], video["url"], video["author"], video["publish_time"], video["raw_text"], now),
        ).fetchone()
        if not row:
            raise RuntimeError(f"failed to upsert video: {video['url']}")
        return int(row[0])

    def video_metadata(self, video_id: int) -> dict:
        row = self.conn.execute(
            "SELECT title, author, publish_time, raw_text, url, keyword FROM videos WHERE id=%s", (video_id,)
        ).fetchone()
        if not row:
            return {}
        return dict(zip(("title", "author", "publish_time", "raw_text", "url", "keyword"), (value or "" for value in row)))

    def existing_spot_names(self, video_id: int) -> set[str]:
        return {str(row[0]) for row in self.conn.execute("SELECT place_name FROM fishing_spots WHERE video_id=%s", (video_id,)) if row[0]}

    def insert_video_comments(self, video_id: int, comments: list[dict]) -> list[dict]:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        saved: list[dict] = []
        for comment in comments:
            values = (
                video_id, comment.get("author", ""), comment.get("text", ""), comment.get("comment_time", ""),
                comment.get("comment_time_raw", ""), comment.get("comment_time_standard", ""),
                comment.get("ip_location", ""), bool(comment.get("is_author")),
                json.dumps(comment, ensure_ascii=False), now,
            )
            row = self.conn.execute(
                """INSERT INTO video_comments(video_id, author, text, comment_time, comment_time_raw,
                                                comment_time_standard, ip_location, is_author, raw_json, collected_at)
                   SELECT %s,%s,%s,%s,%s,%s,%s,%s,%s,%s
                   WHERE NOT EXISTS (
                     SELECT 1 FROM video_comments
                     WHERE video_id=%s AND author=%s AND text=%s AND comment_time_raw=%s
                   )
                   RETURNING id""",
                values + (video_id, comment.get("author", ""), comment.get("text", ""), comment.get("comment_time_raw", "")),
            ).fetchone()
            if not row:
                row = self.conn.execute(
                    """SELECT id FROM video_comments
                       WHERE video_id=%s AND author=%s AND text=%s AND comment_time_raw=%s
                       ORDER BY id LIMIT 1""",
                    (video_id, comment.get("author", ""), comment.get("text", ""), comment.get("comment_time_raw", "")),
                ).fetchone()
            saved_comment = dict(comment)
            if row:
                saved_comment["comment_id"] = int(row[0])
            saved.append(saved_comment)
        return saved

    def insert_comment_keywords(self, video_id: int, keywords: list[dict]) -> list[dict]:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        saved: list[dict] = []
        for item in keywords:
            comment_id = item.get("comment_id")
            keyword = normalize_comment_keyword(item.get("keyword"))
            category = normalize_comment_keyword_category(item.get("category"))
            if not comment_id or not keyword or not category:
                continue
            self.conn.execute(
                """INSERT INTO comment_keywords(video_id, comment_id, keyword, category, confidence, evidence, source, created_at)
                   VALUES(%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT(comment_id, keyword, category) DO NOTHING""",
                (video_id, comment_id, keyword, category, float(item.get("confidence", 0.0) or 0.0),
                 str(item.get("evidence", ""))[:200], "comment_llm", now),
            )
            saved.append({**item, "keyword": keyword, "category": category})
        return saved

    def apply_comment_quality_to_spots(self, video_id: int, quality: dict) -> None:
        quality_score = quality.get("quality_score")
        if quality_score is None:
            return
        self.conn.execute(
            """UPDATE fishing_spots SET quality_score=%s, quality_score_source=%s, quality_score_detail=%s
               WHERE video_id=%s""",
            (quality_score, "comment_llm", quality.get("detail", ""), video_id),
        )

    def upsert_transcript(self, video_id: int, transcript: dict) -> None:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.conn.execute(
            """INSERT INTO video_transcripts(video_id, status, transcript_text, audio_path, srt_path, model,
                                               error, raw_response_path, summary, extras_json, transcribed_at)
               VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
               ON CONFLICT(video_id) DO UPDATE SET
                 status=EXCLUDED.status, transcript_text=EXCLUDED.transcript_text,
                 audio_path=EXCLUDED.audio_path, srt_path=EXCLUDED.srt_path, model=EXCLUDED.model,
                 error=EXCLUDED.error, raw_response_path=EXCLUDED.raw_response_path,
                 summary=EXCLUDED.summary, extras_json=EXCLUDED.extras_json,
                 transcribed_at=EXCLUDED.transcribed_at""",
            (video_id, transcript.get("status", "error"), transcript.get("transcript_text", ""),
             transcript.get("audio_path", ""), transcript.get("srt_path", ""), transcript.get("model", ""),
             transcript.get("error", ""), transcript.get("raw_response_path", ""), transcript.get("summary", ""),
             transcript.get("extras_json", ""), now),
        )

    def transcript_for_video(self, video_id: int) -> dict | None:
        keys = ("video_id", "status", "transcript_text", "audio_path", "srt_path", "model", "error",
                "raw_response_path", "summary", "extras_json", "transcribed_at")
        row = self.conn.execute(
            f"SELECT {', '.join(keys)} FROM video_transcripts WHERE video_id=%s", (video_id,)
        ).fetchone()
        return dict(zip(keys, row)) if row else None

    def videos_with_transcript(self, status: str = "ok", limit: int = 0) -> list[dict]:
        sql = """SELECT v.id, v.url, v.keyword, v.title FROM videos v
                 JOIN video_transcripts t ON t.video_id=v.id WHERE t.status=%s ORDER BY v.id"""
        params: tuple = (status,)
        if limit > 0:
            sql += " LIMIT %s"
            params += (limit,)
        return [{"id": int(r[0]), "url": r[1] or "", "keyword": r[2] or "", "title": r[3] or ""}
                for r in self.conn.execute(sql, params)]

    def videos_pending_transcription(self, limit: int = 0) -> list[dict]:
        sql = """SELECT v.id, v.url, v.keyword, v.title FROM videos v
                 LEFT JOIN video_transcripts t ON t.video_id=v.id
                 WHERE t.id IS NULL OR t.status='error' ORDER BY v.id"""
        params: tuple = ()
        if limit > 0:
            sql += " LIMIT %s"
            params = (limit,)
        return [{"id": int(r[0]), "url": r[1] or "", "keyword": r[2] or "", "title": r[3] or ""}
                for r in self.conn.execute(sql, params)]

    def insert_record(self, keyword: str, video: dict, spot: dict) -> None:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        video_id = self.upsert_video(keyword, video)
        precision = spot.get("precision") or refine_precision(classify_place_name(spot["place_name"]), spot)
        self.conn.execute(
            """INSERT INTO fishing_spots(
                 video_id, place_name, query_name, location, fish_species, fish_species_source,
                 fish_confidence, geocode_score, geocode_level, confidence, source_type, source_text,
                 quality_score, quality_score_source, quality_score_detail, precision, created_at)
               VALUES(%s,%s,%s,ST_SetSRID(ST_MakePoint(%s,%s),4326),%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
            (video_id, spot["place_name"], spot["query_name"], spot["longitude"], spot["latitude"],
             json.dumps(video.get("fish_species", []), ensure_ascii=False), video.get("fish_species_source", ""),
             video.get("fish_confidence", 0.0), spot["geocode_score"], spot["geocode_level"], spot["confidence"],
             spot.get("source_type", "video_text"), spot.get("source_text", video["raw_text"][:500]),
             spot.get("quality_score"), spot.get("quality_score_source", ""), spot.get("quality_score_detail", ""),
             precision, now),
        )
